// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/weilanjin/go-example/ioc/wire/repo"
	"github.com/weilanjin/go-example/ioc/wire/service"
)

// Injectors from wire.go:

func wireApp() *Application {
	aRepo := repo.NewARepo()
	bRepo := repo.NewBRepo()
	cRepo := repo.NewCRepo()
	dRepo := repo.NewDRepo()
	abcdService := service.NewABCDService(aRepo, bRepo, cRepo, dRepo)
	application := NewApplication(abcdService)
	return application
}