// Code generated by "stringer -type=HeroType -trimprefix=HeroType -linecomment"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeroTypeTank-1]
	_ = x[HeroTypeAssassin-2]
	_ = x[HeroTypeMage-3]
}

const _HeroType_name = "TankaaMage"

var _HeroType_index = [...]uint8{0, 4, 6, 10}

func (i HeroType) String() string {
	i -= 1
	if i < 0 || i >= HeroType(len(_HeroType_index)-1) {
		return "HeroType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _HeroType_name[_HeroType_index[i]:_HeroType_index[i+1]]
}
